### ISSUE TITLE
Refresh indicator overlays on list view

### ISSUE THREAD

**Issue by limpep** [aagarwal1012/Liquid-Pull-To-Refresh#46] opened 2020-04-30 22:07 UTC
**Describe the bug**
Hi, when you pull to refresh and the refresh indicator is overlayed on top of the list rather than pushing the list view down as shown in the screencasts on the readme.

**To Reproduce**
1. running latest table version of flutter and dart 

**Expected behavior**
The refresh indicator should push the list view down.

**Screenshots**
<img src="https://user-images.githubusercontent.com/2228477/80763500-8e4b0f00-8b36-11ea-92a5-0efcebb8109c.png" width="200" height="400" />

**Flutter:**
``` Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.815], locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at C:\tools\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
```

**Dart:**
    • Dart version 2.7.2

**Additional context**
`  sdk: ">=2.7.0 <3.0.0"`
`  liquid_pull_to_refresh: ^1.2.0`

```
@override
  Widget build(BuildContext context) {
    final formatter = LastUpdatedDateFormatter(
        lastUpdated: _endpointsData != null
            ? _endpointsData.values[EndPoint.cases]?.date ?? DateTime.now()
            : null);
    return Scaffold(
      appBar: AppBar(
        title: Text("Covid19 Tracker"),
        actions: [
          IconButton(
            icon: Icon(Icons.settings),
            onPressed: () {
              //Navigate to Settings screen
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Settings(),
                ),
              );
            },
          )
        ],
      ),
      body: LiquidPullToRefresh(
        onRefresh: _updateData,
        showChildOpacityTransition: false,
        springAnimationDurationInMilliseconds: 600,
        backgroundColor: Theme.of(context).canvasColor,
        child: ListView(
          children: <Widget>[
            LastUpdatedStatus(
              text: formatter.lastUpdatedStatusText(),
            ),
            for (var endpoint in EndPoint.values)
              EndPointCard(
                endpoint: endpoint,
                value: _endpointsData != null
                    ? _endpointsData.values[endpoint]?.value
                    : null,
              ),
          ],
        ),
      ),
    );
  }
```

**Comment by AadumKhor** [comment] 2020-05-01 11:52
Thank you for pointing this out. The latest commit fdf49fd solves the above issue. 

@aagarwal1012 Please check as it shows an error on while passing the build.

**Comment by aagarwal1012** [comment] 2020-05-01 11:56
@AadumKhor, Travis shows a successful build but codecov shows that it degrades code coverage which we can deal later on. Your commit looks fine to proceed towards creating a Pull Request for the issue.

**Comment by AadumKhor** [comment] 2020-05-01 11:58
@aagarwal1012 I have made the changes directly to the master branch.

**Comment by aagarwal1012** [comment] 2020-05-01 12:00
@AadumKhor, I will not suggest to directly push to master rather try to create a PR next time.

**Comment by AadumKhor** [comment] 2020-05-01 12:02
@aagarwal1012 Ok. Will do in case of further issues.

**Comment by limpep** [comment] 2020-05-01 12:50
So I am guessing a new release needs to be created to be able to tests this?

**Comment by aagarwal1012** [comment] 2020-05-01 13:14
Yes, I will do the release by today.

**Comment by limpep** [comment] 2020-05-02 09:59
Great, look forward to trying the new version. Thanks.

**Comment by AadumKhor** [comment] 2020-05-06 15:34
Closing this since the issue is resolved.

**Closed by AadumKhor** 2020-05-06 15:34 UTC
Labels: bug

**Comment by limpep** [comment] 2020-05-07 12:35
interesting, maybe I have missed the release....

**Comment by dukaric1991** [comment] 2020-05-08 11:49
Any news on new version with this fix :) ?

**Comment by aagarwal1012** [comment] 2020-05-08 14:35
@dukaric1991 @limpep I have published a new version of this package, `v2.0.0`. Have a look at it and please tell us if you have any suggestions.

**Comment by limpep** [comment] 2020-05-08 15:19
@aagarwal1012 I can confirm that it is working now. Thanks, much appreciated.

**Comment by dukaric1991** [comment] 2020-05-11 06:16
@aagarwal1012 i can also confirm that it works as expected! thanks!

**Comment by M4iK26** [comment] 2020-06-29 12:19
I've upgrade from version 1.1.1 to 2.0.0 and now I'm encountering the same problem as mentioned in the original post here.
Do I have to do something special to have the `ListView.builder()` pushed down by the refresh?
